import os
import ROOT as r
from Datacard import *

## working example
dc = Datacard("test", 3, ["zinv", "llep", "qcd"], years=[16,17,18], split_bkg_by_year=True, split_sig_by_year=True)
dc.SetObservation(24)
dc.SetSignalRate(0.516, 16)
dc.SetSignalRate(0.221, 17)
dc.SetSignalRate(0.468, 18)
dc.SetBkgRate(6.0, "zinv", 16)
dc.SetBkgRate(4.0, "zinv", 17)
dc.SetBkgRate(2.0, "zinv", 18)
dc.SetBkgRate(3.0, "llep", 16)
dc.SetBkgRate(2.0, "llep", 17)
dc.SetBkgRate(1.0, "llep", 18)
dc.SetBkgRate(1.0, "qcd", 16)
dc.SetBkgRate(0.5, "qcd", 17)
dc.SetBkgRate(0.25, "qcd", 18)
dc.AddNuisance("lumi_syst", "lnN", split_by_year=True)
dc.SetNuisanceSignalValue("lumi_syst", 1.026, 16)
dc.SetNuisanceSignalValue("lumi_syst", 1.018, 17)
dc.SetNuisanceSignalValue("lumi_syst", 1.036, 18)
dc.AddNuisance("jec", "lnN")
dc.SetNuisanceBkgValue("jec", 1.02, "zinv", 16)
dc.SetNuisanceBkgValue("jec", 1.01, "zinv", 17)
dc.SetNuisanceBkgValue("jec", 1.03, "zinv", 18)
dc.SetNuisanceBkgValue("jec", 1.05, "llep", 16)
dc.SetNuisanceBkgValue("jec", 1.02, "llep", 17)
dc.SetNuisanceBkgValue("jec", 1.04, "llep", 18)
dc.AddNuisance("qcd_JER", "lnN", split_by_year=True)
dc.SetNuisanceBkgValue("qcd_JER", 1.04, "qcd", 16)
dc.SetNuisanceBkgValue("qcd_JER", 0.98, "qcd", 17)
dc.SetNuisanceBkgValue("qcd_JER", 1.05, "qcd", 18)
dc.AddNuisance("zinv_CRstat", "gmN")
dc.SetGMNNuisanceN("zinv_CRstat", 1920)
dc.SetNuisanceBkgValue("zinv_CRstat", 6.0/1920, "zinv", 16) 
dc.SetNuisanceBkgValue("zinv_CRstat", 4.0/1920, "zinv", 17) 
dc.SetNuisanceBkgValue("zinv_CRstat", 2.0/1920, "zinv", 18) 
dc.AddNuisance("llep_CRstat", "gmN")
dc.SetGMNNuisanceN("llep_CRstat", 2)
dc.SetNuisanceBkgValue("llep_CRstat", 3.0/2, "llep", 16) 
dc.SetNuisanceBkgValue("llep_CRstat", 2.0/2, "llep", 17) 
dc.SetNuisanceBkgValue("llep_CRstat", 1.0/2, "llep", 18) 
dc.Write("test.txt")

